spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapi
    username: root
    password: Upen@1988
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    
    
  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        100MB
#  security:
#    user:
#      name: upendra
#      password: Upen@1988

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
        
project.image:
  images/
  
  
logging:
  level:
     org.springframework.web: DEBUG
     guru.springframework.controllers: DEBUG
     org.hibernate: DEBUG
     org: INFO
     